### PR TITLE
Fix: small correction on PlayerRunCmd

### PR DESCRIPTION
**Pull request by Rushaway**

### CODE REVIEW

**Comment by maxime1907** [comment]
It does exactly the same as the condition you changed, so not needed

**Comment by Rushaway** [comment]
I still get some errors with the previous code. That why.

**Comment by maxime1907** [comment]
> I still get some errors with the previous code. That why.

Whats the error ?

**Comment by Rushaway** [comment]
```
L 10/19/2022 - 00:32:20: [SM] Exception reported: Client 14 is not in game
L 10/19/2022 - 00:32:20: [SM] Blaming: zr/zombiereloaded.smx
L 10/19/2022 - 00:32:20: [SM] Call stack trace:
L 10/19/2022 - 00:32:20: [SM]   [0] IsPlayerAlive
L 10/19/2022 - 00:32:20: [SM]   [1] Line 501, zombiereloaded/addons/sourcemod/scripting/zr/playerclasses/apply.inc::Class_OnPlayerRunCmd
L 10/19/2022 - 00:32:20: [SM]   [2] Line 409, zombiereloaded/addons/sourcemod/scripting/zombiereloaded.sp::OnPlayerRunCmd
```

**Comment by Rushaway** [comment]
@maxime1907

**Comment by maxime1907** [comment]
with the latest zr ?

**Comment by Rushaway** [comment]
Yes.

**Comment by maxime1907** [comment]
nah its not the latest version on main ze, we are still using this:
- https://gitlab.com/counterstrikesource/zombiereloaded/-/blob/4b90c7682133f2b0fb402a6eb68d2a6537a6a58d/src/addons/sourcemod/scripting/zr/playerclasses/apply.inc#L501

**Pull request closed without merging**
