### PR TITLE
feat: Publish wiki on GitHub pages

### PR DESCRIPTION
**Pull request by Rushaway**
https://srcdslab.github.io/sm-plugin-zombiereloaded/

### CODE REVIEW

**Comment by maxime1907** [comment]
you need something like this to publish it:
- https://github.com/srcdslab/HandleDumpParser/blob/master/.github/workflows/publish.yaml

**Comment by Rushaway** [comment]
I'm not familiar with dart for GitHub Actions, but that should do the job ?

**Comment by maxime1907** [comment]
ahh no it was just an example^^

here you can run the command to generate the doc instead and put the output inside a folder ./build

**Comment by Rushaway** [comment]
Could you do it instead ? I never worked with pages before and I dont wanna mess anything 🤦

**Comment by maxime1907** [comment]
mhh okay whats the command to generate the doc?

**Comment by Rushaway** [comment]
Can it be merged and published as GitHub page ?

**Comment by maxime1907** [comment]
yes just remove the workflow files and i will configure the repo correctly

**Comment by maxime1907** [comment]
Its now available here:
- https://srcdslab.github.io/sm-plugin-zombiereloaded/web/

**Pull request merged**
